### ISSUE TITLE
Feature request : option to use the form id instead of concatenated label ?

### ISSUE THREAD

**Issue by jy95** [issue-ops/parser#72]
Hello @ncalteen,

First things first, thanks for your hard work this action : quite useful indeed.
I created a couple of [YAML Issue Template](https://github.com/jy95/jy95.github.io/tree/master/.github/ISSUE_TEMPLATE) and was wondering if it was possible to use the id of template instead of the label as key, by some kind of option ? As an option, to preserve your backwards compatibility ofc.

## Example of the to-be

```
steps:
  - name: Parse Issue
    id: parser
    uses: issue-ops/parser@vX.X.X
    with:
      body: ${{ github.event.issue.body }}
      useIdsFromForm: true

  - name: Output Issue JSON
    id: output-issue
    run: echo ${{ steps.parser.outputs.json }}
```

Taking your [example issue template](https://github.com/issue-ops/parser/blob/main/__fixtures__/example/template.yml) and your issue example : 

```md
### The Name of the Thing

this-thing

### The Nickname of the Thing

thing

### The Color of the Thing

blue

### The Shape of the Thing

square

### The Sounds of the Thing

re, mi

### The Topics About the Thing

_No response_

### The Description of the Thing

This is a description.

It has lines.

### The Notes About the Thing

- Note
- Another note
- Lots of notes

### The Code of the Thing

const thing = new Thing()

thing.doThing()

### The String Method of the Code of the Thing

thing.toString()

### Is the Thing a Thing?

- [x] Yes
- [x] No

### Is the Thing Useful?

- [ ] Yes
- [x] Sometimes
- [ ] No

### Read Team

IssueOps-Demo-Readers

### Write Team

IssueOps-Demo-Writers-NotATeam

```

We will get : 

```json
{
  "name": "this-thing",
  "nickname": "thing",
  "color": ["blue"],
  "shape": ["square"],
  "sounds": ["re", "mi"],
  "topics": [],
  "description": "This is a description.\n\nIt has lines.",
  "notes": "- Note\n- Another note\n- Lots of notes",
  "code": "const thing = new Thing()\n\nthing.doThing()",
  "code-string": "thing.toString()",
  "is-thing": {
    "selected": ["Yes"],
    "unselected": ["No"]
  },
  "is-thing-useful": {
    "selected": ["Sometimes"],
    "unselected": ["Yes", "No"]
  },
  "read-team": "IssueOps-Demo-Readers",
  "write-team": "IssueOps-Demo-Writers"
}
```

Thanks in advance
